name: make_it_hot
description: Personal project for people who want to experience new sensations in sex life.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animations: ^2.0.7
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  gradient_progress_indicator: ^1.0.0+5
  multiple_stream_builder: ^3.0.2
  path: ^1.8.2
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  scratcher: ^2.3.0
  shimmer: ^2.0.0
  sqflite: ^2.2.8+2
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/json_data/
