name: make_it_hot
description: Personal project for people who want to experience new sensations in sex life.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.4
  gradient_progress_indicator: ^1.0.0+5
  intl: ^0.17.0
  multiple_stream_builder: ^3.0.2
  path: ^1.8.2
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  scratcher: ^2.3.0
  shimmer: ^2.0.0
  sqflite: ^2.2.8+2
  transparent_image: ^2.0.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/json_data/
    - assets/pos_img/Man On Top/
    - assets/pos_img/Woman On Top/
    - assets/pos_img/Oral/
    # - assets/pos_img/Threesome/
    # - assets/pos_img/Foursome/
    # - assets/pos_img/Spooning/
    - assets/pos_img/Acrobatic/
    - assets/pos_img/Kneeling Or Standing/
    # - assets/pos_img/Anal/
    # - assets/pos_img/Animated/
    # - assets/pos_img/Larger People/
